/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cloudmersive.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Result of a partial email address validation
 **/
@ApiModel(description = "Result of a partial email address validation")
public class AddressGetServersResponse {
  
  @SerializedName("Success")
  private Boolean success = null;
  @SerializedName("Servers")
  private List<String> servers = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getSuccess() {
    return success;
  }
  public void setSuccess(Boolean success) {
    this.success = success;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getServers() {
    return servers;
  }
  public void setServers(List<String> servers) {
    this.servers = servers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddressGetServersResponse addressGetServersResponse = (AddressGetServersResponse) o;
    return (this.success == null ? addressGetServersResponse.success == null : this.success.equals(addressGetServersResponse.success)) &&
        (this.servers == null ? addressGetServersResponse.servers == null : this.servers.equals(addressGetServersResponse.servers));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.success == null ? 0: this.success.hashCode());
    result = 31 * result + (this.servers == null ? 0: this.servers.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddressGetServersResponse {\n");
    
    sb.append("  success: ").append(success).append("\n");
    sb.append("  servers: ").append(servers).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
