/**
 * imageapi
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cloudmersive.client.model;

import com.cloudmersive.client.model.PersonWithAge;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Result from classifying the Age of people in an image
 **/
@ApiModel(description = "Result from classifying the Age of people in an image")
public class AgeDetectionResult {
  
  @SerializedName("Successful")
  private Boolean successful = null;
  @SerializedName("PeopleWithAge")
  private List<PersonWithAge> peopleWithAge = null;
  @SerializedName("PeopleIdentified")
  private Integer peopleIdentified = null;

  /**
   * True if the operation was successful, false otherwise
   **/
  @ApiModelProperty(value = "True if the operation was successful, false otherwise")
  public Boolean getSuccessful() {
    return successful;
  }
  public void setSuccessful(Boolean successful) {
    this.successful = successful;
  }

  /**
   * People in the image annotated with age information
   **/
  @ApiModelProperty(value = "People in the image annotated with age information")
  public List<PersonWithAge> getPeopleWithAge() {
    return peopleWithAge;
  }
  public void setPeopleWithAge(List<PersonWithAge> peopleWithAge) {
    this.peopleWithAge = peopleWithAge;
  }

  /**
   * Number of people identified in the image with an age
   **/
  @ApiModelProperty(value = "Number of people identified in the image with an age")
  public Integer getPeopleIdentified() {
    return peopleIdentified;
  }
  public void setPeopleIdentified(Integer peopleIdentified) {
    this.peopleIdentified = peopleIdentified;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgeDetectionResult ageDetectionResult = (AgeDetectionResult) o;
    return (this.successful == null ? ageDetectionResult.successful == null : this.successful.equals(ageDetectionResult.successful)) &&
        (this.peopleWithAge == null ? ageDetectionResult.peopleWithAge == null : this.peopleWithAge.equals(ageDetectionResult.peopleWithAge)) &&
        (this.peopleIdentified == null ? ageDetectionResult.peopleIdentified == null : this.peopleIdentified.equals(ageDetectionResult.peopleIdentified));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.successful == null ? 0: this.successful.hashCode());
    result = 31 * result + (this.peopleWithAge == null ? 0: this.peopleWithAge.hashCode());
    result = 31 * result + (this.peopleIdentified == null ? 0: this.peopleIdentified.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgeDetectionResult {\n");
    
    sb.append("  successful: ").append(successful).append("\n");
    sb.append("  peopleWithAge: ").append(peopleWithAge).append("\n");
    sb.append("  peopleIdentified: ").append(peopleIdentified).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
