/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cloudmersive.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Result of a validation operation
 **/
@ApiModel(description = "Result of a validation operation")
public class CheckResponse {
  
  @SerializedName("ValidDomain")
  private Boolean validDomain = null;

  /**
   * True if the domain name was valid, false if it is not
   **/
  @ApiModelProperty(value = "True if the domain name was valid, false if it is not")
  public Boolean getValidDomain() {
    return validDomain;
  }
  public void setValidDomain(Boolean validDomain) {
    this.validDomain = validDomain;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckResponse checkResponse = (CheckResponse) o;
    return (this.validDomain == null ? checkResponse.validDomain == null : this.validDomain.equals(checkResponse.validDomain));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.validDomain == null ? 0: this.validDomain.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckResponse {\n");
    
    sb.append("  validDomain: ").append(validDomain).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
