/**
 * nlpapi
 * The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cloudmersive.client.model;

import com.cloudmersive.client.model.CorrectWordInSentenceJsonResponse;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Result of spell checking a sentence
 **/
@ApiModel(description = "Result of spell checking a sentence")
public class CheckSentenceJsonResponse {
  
  @SerializedName("IncorrectCount")
  private Integer incorrectCount = null;
  @SerializedName("Words")
  private List<CorrectWordInSentenceJsonResponse> words = null;

  /**
   * Number of incorrect words
   **/
  @ApiModelProperty(value = "Number of incorrect words")
  public Integer getIncorrectCount() {
    return incorrectCount;
  }
  public void setIncorrectCount(Integer incorrectCount) {
    this.incorrectCount = incorrectCount;
  }

  /**
   * Words in the sentence, both correct and incorrect
   **/
  @ApiModelProperty(value = "Words in the sentence, both correct and incorrect")
  public List<CorrectWordInSentenceJsonResponse> getWords() {
    return words;
  }
  public void setWords(List<CorrectWordInSentenceJsonResponse> words) {
    this.words = words;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckSentenceJsonResponse checkSentenceJsonResponse = (CheckSentenceJsonResponse) o;
    return (this.incorrectCount == null ? checkSentenceJsonResponse.incorrectCount == null : this.incorrectCount.equals(checkSentenceJsonResponse.incorrectCount)) &&
        (this.words == null ? checkSentenceJsonResponse.words == null : this.words.equals(checkSentenceJsonResponse.words));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.incorrectCount == null ? 0: this.incorrectCount.hashCode());
    result = 31 * result + (this.words == null ? 0: this.words.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckSentenceJsonResponse {\n");
    
    sb.append("  incorrectCount: ").append(incorrectCount).append("\n");
    sb.append("  words: ").append(words).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
