/**
 * nlpapi
 * The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cloudmersive.client.model;

import com.cloudmersive.client.model.WordPosition;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * A word in a sentence
 **/
@ApiModel(description = "A word in a sentence")
public class CorrectWordInSentenceJsonResponse {
  
  @SerializedName("Word")
  private WordPosition word = null;
  @SerializedName("Correct")
  private Boolean correct = null;
  @SerializedName("Suggestions")
  private List<String> suggestions = null;

  /**
   * Position of the word
   **/
  @ApiModelProperty(value = "Position of the word")
  public WordPosition getWord() {
    return word;
  }
  public void setWord(WordPosition word) {
    this.word = word;
  }

  /**
   * True if the word is spelled correctly, false otherwise
   **/
  @ApiModelProperty(value = "True if the word is spelled correctly, false otherwise")
  public Boolean getCorrect() {
    return correct;
  }
  public void setCorrect(Boolean correct) {
    this.correct = correct;
  }

  /**
   * Suggested spelling improvements
   **/
  @ApiModelProperty(value = "Suggested spelling improvements")
  public List<String> getSuggestions() {
    return suggestions;
  }
  public void setSuggestions(List<String> suggestions) {
    this.suggestions = suggestions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CorrectWordInSentenceJsonResponse correctWordInSentenceJsonResponse = (CorrectWordInSentenceJsonResponse) o;
    return (this.word == null ? correctWordInSentenceJsonResponse.word == null : this.word.equals(correctWordInSentenceJsonResponse.word)) &&
        (this.correct == null ? correctWordInSentenceJsonResponse.correct == null : this.correct.equals(correctWordInSentenceJsonResponse.correct)) &&
        (this.suggestions == null ? correctWordInSentenceJsonResponse.suggestions == null : this.suggestions.equals(correctWordInSentenceJsonResponse.suggestions));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.word == null ? 0: this.word.hashCode());
    result = 31 * result + (this.correct == null ? 0: this.correct.hashCode());
    result = 31 * result + (this.suggestions == null ? 0: this.suggestions.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CorrectWordInSentenceJsonResponse {\n");
    
    sb.append("  word: ").append(word).append("\n");
    sb.append("  correct: ").append(correct).append("\n");
    sb.append("  suggestions: ").append(suggestions).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
