/**
 * imageapi
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cloudmersive.client.model;

import com.cloudmersive.client.model.DrawTextInstance;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Request to draw one or more pieces of text onto an image
 **/
@ApiModel(description = "Request to draw one or more pieces of text onto an image")
public class DrawTextRequest {
  
  @SerializedName("BaseImageBytes")
  private byte[] baseImageBytes = null;
  @SerializedName("BaseImageUrl")
  private String baseImageUrl = null;
  @SerializedName("TextToDraw")
  private List<DrawTextInstance> textToDraw = null;

  /**
   * Image to draw text on, in bytes.  You can also use the BaseImageUrl instead to supply image input as a URL
   **/
  @ApiModelProperty(value = "Image to draw text on, in bytes.  You can also use the BaseImageUrl instead to supply image input as a URL")
  public byte[] getBaseImageBytes() {
    return baseImageBytes;
  }
  public void setBaseImageBytes(byte[] baseImageBytes) {
    this.baseImageBytes = baseImageBytes;
  }

  /**
   * Image to draw text on, as an HTTP or HTTPS fully-qualified URL
   **/
  @ApiModelProperty(value = "Image to draw text on, as an HTTP or HTTPS fully-qualified URL")
  public String getBaseImageUrl() {
    return baseImageUrl;
  }
  public void setBaseImageUrl(String baseImageUrl) {
    this.baseImageUrl = baseImageUrl;
  }

  /**
   * One or more pieces of text to draw onto the image
   **/
  @ApiModelProperty(value = "One or more pieces of text to draw onto the image")
  public List<DrawTextInstance> getTextToDraw() {
    return textToDraw;
  }
  public void setTextToDraw(List<DrawTextInstance> textToDraw) {
    this.textToDraw = textToDraw;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DrawTextRequest drawTextRequest = (DrawTextRequest) o;
    return (this.baseImageBytes == null ? drawTextRequest.baseImageBytes == null : this.baseImageBytes.equals(drawTextRequest.baseImageBytes)) &&
        (this.baseImageUrl == null ? drawTextRequest.baseImageUrl == null : this.baseImageUrl.equals(drawTextRequest.baseImageUrl)) &&
        (this.textToDraw == null ? drawTextRequest.textToDraw == null : this.textToDraw.equals(drawTextRequest.textToDraw));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.baseImageBytes == null ? 0: this.baseImageBytes.hashCode());
    result = 31 * result + (this.baseImageUrl == null ? 0: this.baseImageUrl.hashCode());
    result = 31 * result + (this.textToDraw == null ? 0: this.textToDraw.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DrawTextRequest {\n");
    
    sb.append("  baseImageBytes: ").append(baseImageBytes).append("\n");
    sb.append("  baseImageUrl: ").append(baseImageUrl).append("\n");
    sb.append("  textToDraw: ").append(textToDraw).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
