/**
 * imageapi
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cloudmersive.client.model;

import com.cloudmersive.client.model.Face;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Results of locating faces in an image
 **/
@ApiModel(description = "Results of locating faces in an image")
public class FaceLocateResponse {
  
  @SerializedName("ErrorDetails")
  private String errorDetails = null;
  @SerializedName("Successful")
  private Boolean successful = null;
  @SerializedName("Faces")
  private List<Face> faces = null;
  @SerializedName("FaceCount")
  private Integer faceCount = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getErrorDetails() {
    return errorDetails;
  }
  public void setErrorDetails(String errorDetails) {
    this.errorDetails = errorDetails;
  }

  /**
   * True if the operation was successful, false otherwise
   **/
  @ApiModelProperty(value = "True if the operation was successful, false otherwise")
  public Boolean getSuccessful() {
    return successful;
  }
  public void setSuccessful(Boolean successful) {
    this.successful = successful;
  }

  /**
   * Array of faces found in the image
   **/
  @ApiModelProperty(value = "Array of faces found in the image")
  public List<Face> getFaces() {
    return faces;
  }
  public void setFaces(List<Face> faces) {
    this.faces = faces;
  }

  /**
   * Number of faces found in the image
   **/
  @ApiModelProperty(value = "Number of faces found in the image")
  public Integer getFaceCount() {
    return faceCount;
  }
  public void setFaceCount(Integer faceCount) {
    this.faceCount = faceCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FaceLocateResponse faceLocateResponse = (FaceLocateResponse) o;
    return (this.errorDetails == null ? faceLocateResponse.errorDetails == null : this.errorDetails.equals(faceLocateResponse.errorDetails)) &&
        (this.successful == null ? faceLocateResponse.successful == null : this.successful.equals(faceLocateResponse.successful)) &&
        (this.faces == null ? faceLocateResponse.faces == null : this.faces.equals(faceLocateResponse.faces)) &&
        (this.faceCount == null ? faceLocateResponse.faceCount == null : this.faceCount.equals(faceLocateResponse.faceCount));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.errorDetails == null ? 0: this.errorDetails.hashCode());
    result = 31 * result + (this.successful == null ? 0: this.successful.hashCode());
    result = 31 * result + (this.faces == null ? 0: this.faces.hashCode());
    result = 31 * result + (this.faceCount == null ? 0: this.faceCount.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class FaceLocateResponse {\n");
    
    sb.append("  errorDetails: ").append(errorDetails).append("\n");
    sb.append("  successful: ").append(successful).append("\n");
    sb.append("  faces: ").append(faces).append("\n");
    sb.append("  faceCount: ").append(faceCount).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
