/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cloudmersive.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Full email addresss validation result
 **/
@ApiModel(description = "Full email addresss validation result")
public class FullEmailValidationResponse {
  
  @SerializedName("ValidAddress")
  private Boolean validAddress = null;
  @SerializedName("MailServerUsedForValidation")
  private String mailServerUsedForValidation = null;

  /**
   * True if the email address is valid, false otherwise
   **/
  @ApiModelProperty(value = "True if the email address is valid, false otherwise")
  public Boolean getValidAddress() {
    return validAddress;
  }
  public void setValidAddress(Boolean validAddress) {
    this.validAddress = validAddress;
  }

  /**
   * Email server connected to for verification
   **/
  @ApiModelProperty(value = "Email server connected to for verification")
  public String getMailServerUsedForValidation() {
    return mailServerUsedForValidation;
  }
  public void setMailServerUsedForValidation(String mailServerUsedForValidation) {
    this.mailServerUsedForValidation = mailServerUsedForValidation;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FullEmailValidationResponse fullEmailValidationResponse = (FullEmailValidationResponse) o;
    return (this.validAddress == null ? fullEmailValidationResponse.validAddress == null : this.validAddress.equals(fullEmailValidationResponse.validAddress)) &&
        (this.mailServerUsedForValidation == null ? fullEmailValidationResponse.mailServerUsedForValidation == null : this.mailServerUsedForValidation.equals(fullEmailValidationResponse.mailServerUsedForValidation));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.validAddress == null ? 0: this.validAddress.hashCode());
    result = 31 * result + (this.mailServerUsedForValidation == null ? 0: this.mailServerUsedForValidation.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class FullEmailValidationResponse {\n");
    
    sb.append("  validAddress: ").append(validAddress).append("\n");
    sb.append("  mailServerUsedForValidation: ").append(mailServerUsedForValidation).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
