/**
 * nlpapi
 * The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cloudmersive.client.model;

import com.cloudmersive.client.model.WordPosition;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Words in input string
 **/
@ApiModel(description = "Words in input string")
public class GetWordsJsonResponse {
  
  @SerializedName("Words")
  private List<WordPosition> words = null;

  /**
   * Array of words
   **/
  @ApiModelProperty(value = "Array of words")
  public List<WordPosition> getWords() {
    return words;
  }
  public void setWords(List<WordPosition> words) {
    this.words = words;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetWordsJsonResponse getWordsJsonResponse = (GetWordsJsonResponse) o;
    return (this.words == null ? getWordsJsonResponse.words == null : this.words.equals(getWordsJsonResponse.words));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.words == null ? 0: this.words.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetWordsJsonResponse {\n");
    
    sb.append("  words: ").append(words).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
