/**
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cloudmersive.client.model;

import com.cloudmersive.client.model.HtmlTemplateOperation;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * HTML template application request
 **/
@ApiModel(description = "HTML template application request")
public class HtmlTemplateApplicationRequest {
  
  @SerializedName("HtmlTemplate")
  private String htmlTemplate = null;
  @SerializedName("HtmlTemplateUrl")
  private String htmlTemplateUrl = null;
  @SerializedName("Operations")
  private List<HtmlTemplateOperation> operations = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getHtmlTemplate() {
    return htmlTemplate;
  }
  public void setHtmlTemplate(String htmlTemplate) {
    this.htmlTemplate = htmlTemplate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getHtmlTemplateUrl() {
    return htmlTemplateUrl;
  }
  public void setHtmlTemplateUrl(String htmlTemplateUrl) {
    this.htmlTemplateUrl = htmlTemplateUrl;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<HtmlTemplateOperation> getOperations() {
    return operations;
  }
  public void setOperations(List<HtmlTemplateOperation> operations) {
    this.operations = operations;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HtmlTemplateApplicationRequest htmlTemplateApplicationRequest = (HtmlTemplateApplicationRequest) o;
    return (this.htmlTemplate == null ? htmlTemplateApplicationRequest.htmlTemplate == null : this.htmlTemplate.equals(htmlTemplateApplicationRequest.htmlTemplate)) &&
        (this.htmlTemplateUrl == null ? htmlTemplateApplicationRequest.htmlTemplateUrl == null : this.htmlTemplateUrl.equals(htmlTemplateApplicationRequest.htmlTemplateUrl)) &&
        (this.operations == null ? htmlTemplateApplicationRequest.operations == null : this.operations.equals(htmlTemplateApplicationRequest.operations));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.htmlTemplate == null ? 0: this.htmlTemplate.hashCode());
    result = 31 * result + (this.htmlTemplateUrl == null ? 0: this.htmlTemplateUrl.hashCode());
    result = 31 * result + (this.operations == null ? 0: this.operations.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class HtmlTemplateApplicationRequest {\n");
    
    sb.append("  htmlTemplate: ").append(htmlTemplate).append("\n");
    sb.append("  htmlTemplateUrl: ").append(htmlTemplateUrl).append("\n");
    sb.append("  operations: ").append(operations).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
