/**
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cloudmersive.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class HtmlTemplateOperation {
  
  public enum ActionEnum {
     1, 
  };
  @SerializedName("Action")
  private ActionEnum action = null;
  @SerializedName("MatchAgsint")
  private String matchAgsint = null;
  @SerializedName("ReplaceWith")
  private String replaceWith = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public ActionEnum getAction() {
    return action;
  }
  public void setAction(ActionEnum action) {
    this.action = action;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMatchAgsint() {
    return matchAgsint;
  }
  public void setMatchAgsint(String matchAgsint) {
    this.matchAgsint = matchAgsint;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getReplaceWith() {
    return replaceWith;
  }
  public void setReplaceWith(String replaceWith) {
    this.replaceWith = replaceWith;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HtmlTemplateOperation htmlTemplateOperation = (HtmlTemplateOperation) o;
    return (this.action == null ? htmlTemplateOperation.action == null : this.action.equals(htmlTemplateOperation.action)) &&
        (this.matchAgsint == null ? htmlTemplateOperation.matchAgsint == null : this.matchAgsint.equals(htmlTemplateOperation.matchAgsint)) &&
        (this.replaceWith == null ? htmlTemplateOperation.replaceWith == null : this.replaceWith.equals(htmlTemplateOperation.replaceWith));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.action == null ? 0: this.action.hashCode());
    result = 31 * result + (this.matchAgsint == null ? 0: this.matchAgsint.hashCode());
    result = 31 * result + (this.replaceWith == null ? 0: this.replaceWith.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class HtmlTemplateOperation {\n");
    
    sb.append("  action: ").append(action).append("\n");
    sb.append("  matchAgsint: ").append(matchAgsint).append("\n");
    sb.append("  replaceWith: ").append(replaceWith).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
