/**
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cloudmersive.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Response from an HTML template application
 **/
@ApiModel(description = "Response from an HTML template application")
public class HtmlTemplateApplicationResponse {
  
  @SerializedName("Successful")
  private Boolean successful = null;
  @SerializedName("FinalHtml")
  private String finalHtml = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getSuccessful() {
    return successful;
  }
  public void setSuccessful(Boolean successful) {
    this.successful = successful;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFinalHtml() {
    return finalHtml;
  }
  public void setFinalHtml(String finalHtml) {
    this.finalHtml = finalHtml;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HtmlTemplateApplicationResponse htmlTemplateApplicationResponse = (HtmlTemplateApplicationResponse) o;
    return (this.successful == null ? htmlTemplateApplicationResponse.successful == null : this.successful.equals(htmlTemplateApplicationResponse.successful)) &&
        (this.finalHtml == null ? htmlTemplateApplicationResponse.finalHtml == null : this.finalHtml.equals(htmlTemplateApplicationResponse.finalHtml));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.successful == null ? 0: this.successful.hashCode());
    result = 31 * result + (this.finalHtml == null ? 0: this.finalHtml.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class HtmlTemplateApplicationResponse {\n");
    
    sb.append("  successful: ").append(successful).append("\n");
    sb.append("  finalHtml: ").append(finalHtml).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
