/**
 * ocrapi
 * The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cloudmersive.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Response from an OCR to text operation.  Includes the confience rating and converted text result.
 **/
@ApiModel(description = "Response from an OCR to text operation.  Includes the confience rating and converted text result.")
public class ImageToTextResponse {
  
  @SerializedName("MeanConfidenceLevel")
  private Float meanConfidenceLevel = null;
  @SerializedName("TextResult")
  private String textResult = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Float getMeanConfidenceLevel() {
    return meanConfidenceLevel;
  }
  public void setMeanConfidenceLevel(Float meanConfidenceLevel) {
    this.meanConfidenceLevel = meanConfidenceLevel;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTextResult() {
    return textResult;
  }
  public void setTextResult(String textResult) {
    this.textResult = textResult;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImageToTextResponse imageToTextResponse = (ImageToTextResponse) o;
    return (this.meanConfidenceLevel == null ? imageToTextResponse.meanConfidenceLevel == null : this.meanConfidenceLevel.equals(imageToTextResponse.meanConfidenceLevel)) &&
        (this.textResult == null ? imageToTextResponse.textResult == null : this.textResult.equals(imageToTextResponse.textResult));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.meanConfidenceLevel == null ? 0: this.meanConfidenceLevel.hashCode());
    result = 31 * result + (this.textResult == null ? 0: this.textResult.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImageToTextResponse {\n");
    
    sb.append("  meanConfidenceLevel: ").append(meanConfidenceLevel).append("\n");
    sb.append("  textResult: ").append(textResult).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
