/**
 * nlpapi
 * The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cloudmersive.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Output of a language detection operation
 **/
@ApiModel(description = "Output of a language detection operation")
public class LanguageDetectionResponse {
  
  @SerializedName("Successful")
  private Boolean successful = null;
  @SerializedName("DetectedLanguage_ThreeLetterCode")
  private String detectedLanguageThreeLetterCode = null;
  @SerializedName("DetectedLanguage_FullName")
  private String detectedLanguageFullName = null;

  /**
   * True if the language detection operation was successful, false otherwise
   **/
  @ApiModelProperty(value = "True if the language detection operation was successful, false otherwise")
  public Boolean getSuccessful() {
    return successful;
  }
  public void setSuccessful(Boolean successful) {
    this.successful = successful;
  }

  /**
   * ISO 639 three letter language code
   **/
  @ApiModelProperty(value = "ISO 639 three letter language code")
  public String getDetectedLanguageThreeLetterCode() {
    return detectedLanguageThreeLetterCode;
  }
  public void setDetectedLanguageThreeLetterCode(String detectedLanguageThreeLetterCode) {
    this.detectedLanguageThreeLetterCode = detectedLanguageThreeLetterCode;
  }

  /**
   * The full name (in English) of the detected language
   **/
  @ApiModelProperty(value = "The full name (in English) of the detected language")
  public String getDetectedLanguageFullName() {
    return detectedLanguageFullName;
  }
  public void setDetectedLanguageFullName(String detectedLanguageFullName) {
    this.detectedLanguageFullName = detectedLanguageFullName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LanguageDetectionResponse languageDetectionResponse = (LanguageDetectionResponse) o;
    return (this.successful == null ? languageDetectionResponse.successful == null : this.successful.equals(languageDetectionResponse.successful)) &&
        (this.detectedLanguageThreeLetterCode == null ? languageDetectionResponse.detectedLanguageThreeLetterCode == null : this.detectedLanguageThreeLetterCode.equals(languageDetectionResponse.detectedLanguageThreeLetterCode)) &&
        (this.detectedLanguageFullName == null ? languageDetectionResponse.detectedLanguageFullName == null : this.detectedLanguageFullName.equals(languageDetectionResponse.detectedLanguageFullName));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.successful == null ? 0: this.successful.hashCode());
    result = 31 * result + (this.detectedLanguageThreeLetterCode == null ? 0: this.detectedLanguageThreeLetterCode.hashCode());
    result = 31 * result + (this.detectedLanguageFullName == null ? 0: this.detectedLanguageFullName.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LanguageDetectionResponse {\n");
    
    sb.append("  successful: ").append(successful).append("\n");
    sb.append("  detectedLanguageThreeLetterCode: ").append(detectedLanguageThreeLetterCode).append("\n");
    sb.append("  detectedLanguageFullName: ").append(detectedLanguageFullName).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
