/**
 * imageapi
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cloudmersive.client.model;

import com.cloudmersive.client.model.Face;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * A person identified in an image age classification operation
 **/
@ApiModel(description = "A person identified in an image age classification operation")
public class PersonWithAge {
  
  @SerializedName("FaceLocation")
  private Face faceLocation = null;
  @SerializedName("AgeClassificationConfidence")
  private Double ageClassificationConfidence = null;
  @SerializedName("AgeClass")
  private String ageClass = null;

  /**
   * Location and other information about the person's face corresponding to this age classification
   **/
  @ApiModelProperty(value = "Location and other information about the person's face corresponding to this age classification")
  public Face getFaceLocation() {
    return faceLocation;
  }
  public void setFaceLocation(Face faceLocation) {
    this.faceLocation = faceLocation;
  }

  /**
   * Confidence level of age classification; possible values are between 0.0 and 1.0; higher is better, with values &gt; 0.50 being high confidence results
   **/
  @ApiModelProperty(value = "Confidence level of age classification; possible values are between 0.0 and 1.0; higher is better, with values &gt; 0.50 being high confidence results")
  public Double getAgeClassificationConfidence() {
    return ageClassificationConfidence;
  }
  public void setAgeClassificationConfidence(Double ageClassificationConfidence) {
    this.ageClassificationConfidence = ageClassificationConfidence;
  }

  /**
   * The person's age range classification result in years; possible values are \"0-2\", \"4-6\", \"8-13\", \"15-20\", \"25-32\", \"38-43\", \"48-53\", \"60+\"
   **/
  @ApiModelProperty(value = "The person's age range classification result in years; possible values are \"0-2\", \"4-6\", \"8-13\", \"15-20\", \"25-32\", \"38-43\", \"48-53\", \"60+\"")
  public String getAgeClass() {
    return ageClass;
  }
  public void setAgeClass(String ageClass) {
    this.ageClass = ageClass;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonWithAge personWithAge = (PersonWithAge) o;
    return (this.faceLocation == null ? personWithAge.faceLocation == null : this.faceLocation.equals(personWithAge.faceLocation)) &&
        (this.ageClassificationConfidence == null ? personWithAge.ageClassificationConfidence == null : this.ageClassificationConfidence.equals(personWithAge.ageClassificationConfidence)) &&
        (this.ageClass == null ? personWithAge.ageClass == null : this.ageClass.equals(personWithAge.ageClass));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.faceLocation == null ? 0: this.faceLocation.hashCode());
    result = 31 * result + (this.ageClassificationConfidence == null ? 0: this.ageClassificationConfidence.hashCode());
    result = 31 * result + (this.ageClass == null ? 0: this.ageClass.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonWithAge {\n");
    
    sb.append("  faceLocation: ").append(faceLocation).append("\n");
    sb.append("  ageClassificationConfidence: ").append(ageClassificationConfidence).append("\n");
    sb.append("  ageClass: ").append(ageClass).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
