/**
 * nlpapi
 * The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cloudmersive.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Part of speech tagging request
 **/
@ApiModel(description = "Part of speech tagging request")
public class PosRequest {
  
  @SerializedName("InputText")
  private String inputText = null;

  /**
   * Input text string
   **/
  @ApiModelProperty(value = "Input text string")
  public String getInputText() {
    return inputText;
  }
  public void setInputText(String inputText) {
    this.inputText = inputText;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PosRequest posRequest = (PosRequest) o;
    return (this.inputText == null ? posRequest.inputText == null : this.inputText.equals(posRequest.inputText));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.inputText == null ? 0: this.inputText.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PosRequest {\n");
    
    sb.append("  inputText: ").append(inputText).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
