/**
 * nlpapi
 * The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cloudmersive.client.model;

import com.cloudmersive.client.model.PosSentence;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Part of speech tag result
 **/
@ApiModel(description = "Part of speech tag result")
public class PosResponse {
  
  @SerializedName("TaggedSentences")
  private List<PosSentence> taggedSentences = null;

  /**
   * Sentences in the string
   **/
  @ApiModelProperty(value = "Sentences in the string")
  public List<PosSentence> getTaggedSentences() {
    return taggedSentences;
  }
  public void setTaggedSentences(List<PosSentence> taggedSentences) {
    this.taggedSentences = taggedSentences;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PosResponse posResponse = (PosResponse) o;
    return (this.taggedSentences == null ? posResponse.taggedSentences == null : this.taggedSentences.equals(posResponse.taggedSentences));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.taggedSentences == null ? 0: this.taggedSentences.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PosResponse {\n");
    
    sb.append("  taggedSentences: ").append(taggedSentences).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
