/**
 * nlpapi
 * The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cloudmersive.client.model;

import com.cloudmersive.client.model.PosTaggedWord;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Sentence in a POS tag result
 **/
@ApiModel(description = "Sentence in a POS tag result")
public class PosSentence {
  
  @SerializedName("Words")
  private List<PosTaggedWord> words = null;

  /**
   * Words in the sentence
   **/
  @ApiModelProperty(value = "Words in the sentence")
  public List<PosTaggedWord> getWords() {
    return words;
  }
  public void setWords(List<PosTaggedWord> words) {
    this.words = words;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PosSentence posSentence = (PosSentence) o;
    return (this.words == null ? posSentence.words == null : this.words.equals(posSentence.words));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.words == null ? 0: this.words.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PosSentence {\n");
    
    sb.append("  words: ").append(words).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
