/**
 * barcodeapi
 * Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cloudmersive.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ProductMatch {
  
  @SerializedName("EAN")
  private String EAN = null;
  @SerializedName("Title")
  private String title = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEAN() {
    return EAN;
  }
  public void setEAN(String EAN) {
    this.EAN = EAN;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductMatch productMatch = (ProductMatch) o;
    return (this.EAN == null ? productMatch.EAN == null : this.EAN.equals(productMatch.EAN)) &&
        (this.title == null ? productMatch.title == null : this.title.equals(productMatch.title));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.EAN == null ? 0: this.EAN.hashCode());
    result = 31 * result + (this.title == null ? 0: this.title.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductMatch {\n");
    
    sb.append("  EAN: ").append(EAN).append("\n");
    sb.append("  title: ").append(title).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
