/**
 * imageapi
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cloudmersive.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Specific recognition outcome
 **/
@ApiModel(description = "Specific recognition outcome")
public class RecognitionOutcome {
  
  @SerializedName("ConfidenceScore")
  private Double confidenceScore = null;
  @SerializedName("Description")
  private String description = null;

  /**
   * Scores closer to 1 are better than scores closer to 0
   **/
  @ApiModelProperty(value = "Scores closer to 1 are better than scores closer to 0")
  public Double getConfidenceScore() {
    return confidenceScore;
  }
  public void setConfidenceScore(Double confidenceScore) {
    this.confidenceScore = confidenceScore;
  }

  /**
   * English language description of the image
   **/
  @ApiModelProperty(value = "English language description of the image")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecognitionOutcome recognitionOutcome = (RecognitionOutcome) o;
    return (this.confidenceScore == null ? recognitionOutcome.confidenceScore == null : this.confidenceScore.equals(recognitionOutcome.confidenceScore)) &&
        (this.description == null ? recognitionOutcome.description == null : this.description.equals(recognitionOutcome.description));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.confidenceScore == null ? 0: this.confidenceScore.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecognitionOutcome {\n");
    
    sb.append("  confidenceScore: ").append(confidenceScore).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
