/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cloudmersive.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class VatLookupResponse {
  
  @SerializedName("CountryCode")
  private String countryCode = null;
  @SerializedName("VatNumber")
  private String vatNumber = null;
  @SerializedName("IsValid")
  private Boolean isValid = null;
  @SerializedName("BusinessName")
  private String businessName = null;
  @SerializedName("BusinessAddress")
  private String businessAddress = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCountryCode() {
    return countryCode;
  }
  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getVatNumber() {
    return vatNumber;
  }
  public void setVatNumber(String vatNumber) {
    this.vatNumber = vatNumber;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getIsValid() {
    return isValid;
  }
  public void setIsValid(Boolean isValid) {
    this.isValid = isValid;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getBusinessName() {
    return businessName;
  }
  public void setBusinessName(String businessName) {
    this.businessName = businessName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getBusinessAddress() {
    return businessAddress;
  }
  public void setBusinessAddress(String businessAddress) {
    this.businessAddress = businessAddress;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VatLookupResponse vatLookupResponse = (VatLookupResponse) o;
    return (this.countryCode == null ? vatLookupResponse.countryCode == null : this.countryCode.equals(vatLookupResponse.countryCode)) &&
        (this.vatNumber == null ? vatLookupResponse.vatNumber == null : this.vatNumber.equals(vatLookupResponse.vatNumber)) &&
        (this.isValid == null ? vatLookupResponse.isValid == null : this.isValid.equals(vatLookupResponse.isValid)) &&
        (this.businessName == null ? vatLookupResponse.businessName == null : this.businessName.equals(vatLookupResponse.businessName)) &&
        (this.businessAddress == null ? vatLookupResponse.businessAddress == null : this.businessAddress.equals(vatLookupResponse.businessAddress));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.countryCode == null ? 0: this.countryCode.hashCode());
    result = 31 * result + (this.vatNumber == null ? 0: this.vatNumber.hashCode());
    result = 31 * result + (this.isValid == null ? 0: this.isValid.hashCode());
    result = 31 * result + (this.businessName == null ? 0: this.businessName.hashCode());
    result = 31 * result + (this.businessAddress == null ? 0: this.businessAddress.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class VatLookupResponse {\n");
    
    sb.append("  countryCode: ").append(countryCode).append("\n");
    sb.append("  vatNumber: ").append(vatNumber).append("\n");
    sb.append("  isValid: ").append(isValid).append("\n");
    sb.append("  businessName: ").append(businessName).append("\n");
    sb.append("  businessAddress: ").append(businessAddress).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
