/**
 * virusapi
 * Virus API lets you scan files and content for viruses and identify security issues with content.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cloudmersive.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Virus positively identified
 **/
@ApiModel(description = "Virus positively identified")
public class VirusFound {
  
  @SerializedName("FileName")
  private String fileName = null;
  @SerializedName("VirusName")
  private String virusName = null;

  /**
   * Name of the file containing the virus
   **/
  @ApiModelProperty(value = "Name of the file containing the virus")
  public String getFileName() {
    return fileName;
  }
  public void setFileName(String fileName) {
    this.fileName = fileName;
  }

  /**
   * Name of the virus that was found
   **/
  @ApiModelProperty(value = "Name of the virus that was found")
  public String getVirusName() {
    return virusName;
  }
  public void setVirusName(String virusName) {
    this.virusName = virusName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VirusFound virusFound = (VirusFound) o;
    return (this.fileName == null ? virusFound.fileName == null : this.fileName.equals(virusFound.fileName)) &&
        (this.virusName == null ? virusFound.virusName == null : this.virusName.equals(virusFound.virusName));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.fileName == null ? 0: this.fileName.hashCode());
    result = 31 * result + (this.virusName == null ? 0: this.virusName.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class VirusFound {\n");
    
    sb.append("  fileName: ").append(fileName).append("\n");
    sb.append("  virusName: ").append(virusName).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
