/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cloudmersive.client.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Result of a WHOIS operation
 **/
@ApiModel(description = "Result of a WHOIS operation")
public class WhoisResponse {
  
  @SerializedName("ValidDomain")
  private Boolean validDomain = null;
  @SerializedName("WhoisServer")
  private String whoisServer = null;
  @SerializedName("RawTextRecord")
  private String rawTextRecord = null;
  @SerializedName("CreatedDt")
  private Date createdDt = null;

  /**
   * True if the domain is valid, false if it is not
   **/
  @ApiModelProperty(value = "True if the domain is valid, false if it is not")
  public Boolean getValidDomain() {
    return validDomain;
  }
  public void setValidDomain(Boolean validDomain) {
    this.validDomain = validDomain;
  }

  /**
   * Server used to lookup WHOIS information (may change based on lookup).
   **/
  @ApiModelProperty(value = "Server used to lookup WHOIS information (may change based on lookup).")
  public String getWhoisServer() {
    return whoisServer;
  }
  public void setWhoisServer(String whoisServer) {
    this.whoisServer = whoisServer;
  }

  /**
   * WHOIS raw text record
   **/
  @ApiModelProperty(value = "WHOIS raw text record")
  public String getRawTextRecord() {
    return rawTextRecord;
  }
  public void setRawTextRecord(String rawTextRecord) {
    this.rawTextRecord = rawTextRecord;
  }

  /**
   * Creation date for the record
   **/
  @ApiModelProperty(value = "Creation date for the record")
  public Date getCreatedDt() {
    return createdDt;
  }
  public void setCreatedDt(Date createdDt) {
    this.createdDt = createdDt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WhoisResponse whoisResponse = (WhoisResponse) o;
    return (this.validDomain == null ? whoisResponse.validDomain == null : this.validDomain.equals(whoisResponse.validDomain)) &&
        (this.whoisServer == null ? whoisResponse.whoisServer == null : this.whoisServer.equals(whoisResponse.whoisServer)) &&
        (this.rawTextRecord == null ? whoisResponse.rawTextRecord == null : this.rawTextRecord.equals(whoisResponse.rawTextRecord)) &&
        (this.createdDt == null ? whoisResponse.createdDt == null : this.createdDt.equals(whoisResponse.createdDt));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.validDomain == null ? 0: this.validDomain.hashCode());
    result = 31 * result + (this.whoisServer == null ? 0: this.whoisServer.hashCode());
    result = 31 * result + (this.rawTextRecord == null ? 0: this.rawTextRecord.hashCode());
    result = 31 * result + (this.createdDt == null ? 0: this.createdDt.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class WhoisResponse {\n");
    
    sb.append("  validDomain: ").append(validDomain).append("\n");
    sb.append("  whoisServer: ").append(whoisServer).append("\n");
    sb.append("  rawTextRecord: ").append(rawTextRecord).append("\n");
    sb.append("  createdDt: ").append(createdDt).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
