/**
 * nlpapi
 * The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cloudmersive.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class WordPosition {
  
  @SerializedName("Word")
  private String word = null;
  @SerializedName("WordIndex")
  private Integer wordIndex = null;
  @SerializedName("StartPosition")
  private Integer startPosition = null;
  @SerializedName("EndPosition")
  private Integer endPosition = null;

  /**
   * Word as a string
   **/
  @ApiModelProperty(value = "Word as a string")
  public String getWord() {
    return word;
  }
  public void setWord(String word) {
    this.word = word;
  }

  /**
   * Zero-based index of the word; first word has index 0, second word has index 1 and so on
   **/
  @ApiModelProperty(value = "Zero-based index of the word; first word has index 0, second word has index 1 and so on")
  public Integer getWordIndex() {
    return wordIndex;
  }
  public void setWordIndex(Integer wordIndex) {
    this.wordIndex = wordIndex;
  }

  /**
   * Zero-based character offset at which the word begins in the input string
   **/
  @ApiModelProperty(value = "Zero-based character offset at which the word begins in the input string")
  public Integer getStartPosition() {
    return startPosition;
  }
  public void setStartPosition(Integer startPosition) {
    this.startPosition = startPosition;
  }

  /**
   * Zero-based character offset at which the word ends in the input string
   **/
  @ApiModelProperty(value = "Zero-based character offset at which the word ends in the input string")
  public Integer getEndPosition() {
    return endPosition;
  }
  public void setEndPosition(Integer endPosition) {
    this.endPosition = endPosition;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WordPosition wordPosition = (WordPosition) o;
    return (this.word == null ? wordPosition.word == null : this.word.equals(wordPosition.word)) &&
        (this.wordIndex == null ? wordPosition.wordIndex == null : this.wordIndex.equals(wordPosition.wordIndex)) &&
        (this.startPosition == null ? wordPosition.startPosition == null : this.startPosition.equals(wordPosition.startPosition)) &&
        (this.endPosition == null ? wordPosition.endPosition == null : this.endPosition.equals(wordPosition.endPosition));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.word == null ? 0: this.word.hashCode());
    result = 31 * result + (this.wordIndex == null ? 0: this.wordIndex.hashCode());
    result = 31 * result + (this.startPosition == null ? 0: this.startPosition.hashCode());
    result = 31 * result + (this.endPosition == null ? 0: this.endPosition.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class WordPosition {\n");
    
    sb.append("  word: ").append(word).append("\n");
    sb.append("  wordIndex: ").append(wordIndex).append("\n");
    sb.append("  startPosition: ").append(startPosition).append("\n");
    sb.append("  endPosition: ").append(endPosition).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
